# Generated by Django 4.2.1 on 2023-08-26 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX idx_unique_active_user ON authapp_user_token(user_id)"
                "WHERE active is TRUE;"
            ),
            reverse_sql="DROP INDEX idx_unique_active_user;"
        )
    ]
